create table person
(
    id integer generated by default as identity primary key,
    username varchar not null unique,
    password varchar not null,
    description text,
    role varchar not null
);